# Generated by Django 5.0.7 on 2024-07-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                ("call_id", models.AutoField(primary_key=True, serialize=False)),
                ("call_name", models.CharField(max_length=255, unique=True)),
                ("dataset_name", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=255)),
                ("status", models.CharField(default="OPEN", max_length=255)),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fact_calls",
                "indexes": [models.Index(fields=["call_name"], name="idx_call_name")],
            },
        ),
        migrations.CreateModel(
            name="CallTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("call_id", models.BigIntegerField()),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("task_name", models.CharField(max_length=255)),
                ("task_args", models.TextField(default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FAILURE", "FAILURE"),
                            ("PENDING", "PENDING"),
                            ("RECEIVED", "RECEIVED"),
                            ("RETRY", "RETRY"),
                            ("REVOKED", "REVOKED"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                        ],
                        default="PENDING",
                        max_length=255,
                    ),
                ),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("traceback", models.TextField(default="")),
            ],
            options={
                "db_table": "fact_calls_tasks",
                "indexes": [
                    models.Index(fields=["call_id"], name="idx_calls_tasks_call_id"),
                    models.Index(fields=["task_id"], name="idx_calls_tasks_task_id"),
                ],
            },
        ),
    ]
