# Generated by Django 5.0.7 on 2024-10-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                ("call_id", models.AutoField(primary_key=True, serialize=False)),
                ("call_name", models.CharField(max_length=255, unique=True)),
                ("dataset_name", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=255)),
                ("status", models.CharField(default="OPEN", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tx_calls",
                "indexes": [models.Index(fields=["call_name"], name="idx_call_name")],
            },
        ),
        migrations.CreateModel(
            name="CallJob",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("call_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(default="PENDING", max_length=255)),
                ("params", models.JSONField()),
                ("results_dir", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("traceback", models.TextField(default="")),
            ],
            options={
                "db_table": "tx_call_jobs",
                "indexes": [
                    models.Index(fields=["call_id"], name="idx_ch_call_id"),
                    models.Index(fields=["name"], name="idx_ch_name"),
                    models.Index(fields=["status"], name="idx_ch_status"),
                ],
            },
        ),
    ]
