kind: Secret
apiVersion: v1
metadata:
  name: dc3-backend-secrets
  namespace: cms-dc3-prod
type: Opaque
data:
  DJANGO_SECRET_KEY:
  DJANGO_DATABASE_URI:
  DJANGO_CELERY_BROKER_URL:
  DJANGO_CELERY_RESULT_BACKEND:
  DJANGO_KEYCLOAK_CONFIDENTIAL_CLIENT_ID:
  DJANGO_KEYCLOAK_CONFIDENTIAL_SECRET_KEY:
  DJANGO_KEYTAB_USR:
  DJANGO_KEYTAB_PWD:
  DJANGO_RR_SSO_CLIENT_SECRET:
  DJANGO_RR_SSO_CLIENT_ID:
  DJANGO_CERT_FPATH:
  DJANGO_KEY_FPATH:
  DJANGO_BASE_LOCAL_RESULTS_DIR:
  DJANGO_CONDOR_CERT_FPATH:
  DJANGO_CONDOR_KEY_FPATH:
  DJANGO_BASE_CONDOR_WORK_DIR:
  DJANGO_BASE_CONDOR_RESULTS_DIR:
