# Generated by Django 5.0.7 on 2024-10-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("params", models.JSONField()),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="PENDING", max_length=255)),
                ("results_dir", models.TextField(default="")),
                ("traceback", models.TextField(default="")),
            ],
            options={
                "db_table": "tx_jobs",
                "indexes": [
                    models.Index(fields=["name"], name="idx_tx_jobs_name"),
                    models.Index(fields=["action"], name="idx_tx_jobs_action"),
                    models.Index(fields=["created_by"], name="idx_tx_jobs_created_by"),
                    models.Index(fields=["status"], name="idx_tx_jobs_status"),
                ],
            },
        ),
    ]
